import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className={`max-w-5xl mx-auto`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`bg-gray-200 p-4 m-4`}>
        <h1 className={`text-2xl font-bold text-center`}>
          Hello from Nextjs and Tailwind
        </h1>
      </main>
    </div>
  );
};

export default Home;
